# Generated by Django 2.1.2 on 2019-04-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item2',
            name='name',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, null=True),
        ),
    ]
