# Generated by Django 2.1.2 on 2019-04-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item1',
            options={'verbose_name': '一次評価', 'verbose_name_plural': '一次評価'},
        ),
    ]
