# Generated by Django 2.1.2 on 2019-04-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190426_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item1',
            options={'verbose_name': 'item1', 'verbose_name_plural': 'item1'},
        ),
    ]
