# Generated by Django 2.1.2 on 2019-06-08 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190608_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Q1_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【コミュニケーション力】（情報伝達・発信力）<br>        自分の考えを相手に応じてわかりやすく的確に伝えられる。        組織において必要な情報を、的確にわかりやすく正確に伝える力。        自己の理論や企画を実行に移すために、関係者を説得、調整する力<br><br>        （１）自分の考えを相手に応じて、わかりやすく的確に伝えることができ、        また要点をついた説明ができる。'),
        ),
    ]
