# Generated by Django 2.1.2 on 2019-06-09 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190609_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Q1_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）業務が滞りなく行われるように、他部門との連携・調整がスムーズにできる。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q1_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）他部門（現場）が業務を円滑に進められるよう必要なサポートを行いまた、わかりやすい情報提供を行っている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q1_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）周りの空気を読み、自部署内および現場を含め法人全体の業務が円滑に進むための横串としての調整力に長けている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q1_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）相手の言いたいことをきちんと聞き、理解できている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q2_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【責任感】<br>        自己の責任を意識しそれを果たそうとする力<br><br>        （１）自分の失敗はチームの失敗であり、チームの失敗は、自分の失敗であると捉えて行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q2_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）自分の責任の範囲をきちんと理解し、自分の行う行動や行為、言動に責任を持った発言や行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q2_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）問題や課題に対して、自分事として捉え、他責にすることなく対処することができる。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q2_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）問題や課題に対して、自分事として捉え、他責にすることなく対処することができる。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q2_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）やや困難な状況に直面しても責任を回避したり、途中で挫折することはなく自己の任務を遂行している。'),
        ),
    ]
