# Generated by Django 2.1.2 on 2019-06-09 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190609_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Q3_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【人材育成】<br>        チームメンバーのやる気と生産性を高め、一人ひとりの成長を促す力<br><br>        （１）部下の意見に耳を傾け、部下に対し勇気づけや仕事への動機づけをはかっている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q3_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）組織運営において、メンバー一人ひとりの能力を把握し、部署目標達成のために的確な役割分担と指示、指導を行っている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q3_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）メンバーの先頭に立ち、より良いものを目指す心持ちや姿勢を、日常の発言や行動から模範を示している。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q3_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）自分の発する言葉の重要性を意識した上で、部署のビジョン・方向性を示す機会を定期的につくりメンバーと共有している。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q3_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）チーム全員が協力して目標に向かうよう団結力とやる気を高めるための定期的な面談やミーティングを実施している。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q4_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【企画推進力】<br>        長期的視点での部署運営より高い課題、ハードルに挑戦し克服していこうとする力<br><br>        （１）現状に満足することなく、何事にも積極的に新しいことへ挑戦し成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q4_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）物事、状況を常により良く改善していこうという意識を持ち、それを日々の行動にうつしている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q4_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）自分たちの顧客は誰か、エンドユーザーは誰かを常に考え、そのニーズに応えるために迅速かつ積極的に対応している。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q4_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）現場のニーズを常に把握し、現場力が最大限に発揮されるために必要なものは何かを判断し提供している。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q4_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）状況に最も適したタイミングの良い計画・スケジュール化ができている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q5_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【経営感覚・経営貢献】<br>        業績に関心を持ち自部署だけでなく法人の利益のための広い視野で物事を考える力<br><br>        （１）法人の業績に関心を持ち、自分や自部署だけでなく法人全体の利益のためにというひろい視野で物事を考えている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q5_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）組織全体に利益をもたらす意思決定（意思決定のための調整も含め）がすばやくできる。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q5_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）経営方針を理解し、貢献を意識した部署目標を設定し、部署としての成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q5_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）組織の長期的な利益に対しては、自部署の短期的利益も犠牲にできる視点を持った発言、行動、判断ができている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q5_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）リスクマネジメント、医療事故防止、院内感染対策の必要性を理解し安全管理の方策を身につけ危機管理に積極的に参加している。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q6_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【マネジメント力・組織管理能力】<br>        表面的な情報だけでなく、自分自身の考察を加え、真の課題、問題を的確に捉え、解決策を見出し、チーム全体で行動を促す力<br><br>        （１）仕事の進行につき問題が生じないように常に気を配り、部下への助言や援助を行っている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q6_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）常に広い問題意識を持っており、現在の仕事に問題が生じそうなときは早め早めに手を打っている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q6_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）自らの感情をコントロールするだけでなく、周りの落ち着きも取り戻せるよう冷静に対処している。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q6_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）管理者としての役割を強く自覚しており、部下に対して模範となる行動・言動ができている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q6_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）複雑・困難な問題や突発的事態に対し、自己の責任において臨機応変な処置をとることができている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q1_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【コミュニケーション力】（情報伝達・発信力）<br>        自分の考えを相手に応じてわかりやすく的確に伝えられる。        組織において必要な情報を、的確にわかりやすく正確に伝える力。        自己の理論や企画を実行に移すために、関係者を説得、調整する力<br><br>        （１）自分の考えを相手に応じて、わかりやすく的確に伝えることができ、        また要点をついた説明ができる。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q1_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）業務が滞りなく行われるように、他部門との連携・調整がスムーズにできる。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q1_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）他部門（現場）が業務を円滑に進められるよう必要なサポートを行いまた、わかりやすい情報提供を行っている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q1_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）周りの空気を読み、自部署内および現場を含め法人全体の業務が円滑に進むための横串としての調整力に長けている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q1_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）相手の言いたいことをきちんと聞き、理解できている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q2_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【責任感】<br>        自己の責任を意識しそれを果たそうとする力<br><br>        （１）自分の失敗はチームの失敗であり、チームの失敗は、自分の失敗であると捉えて行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q2_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）自分の責任の範囲をきちんと理解し、自分の行う行動や行為、言動に責任を持った発言や行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q2_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）問題や課題に対して、自分事として捉え、他責にすることなく対処することができる。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q2_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）問題や課題に対して、自分事として捉え、他責にすることなく対処することができる。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q2_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）やや困難な状況に直面しても責任を回避したり、途中で挫折することはなく自己の任務を遂行している。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q3_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【人材育成】<br>        チームメンバーのやる気と生産性を高め、一人ひとりの成長を促す力<br><br>        （１）部下の意見に耳を傾け、部下に対し勇気づけや仕事への動機づけをはかっている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q3_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）組織運営において、メンバー一人ひとりの能力を把握し、部署目標達成のために的確な役割分担と指示、指導を行っている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q3_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）メンバーの先頭に立ち、より良いものを目指す心持ちや姿勢を、日常の発言や行動から模範を示している。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q3_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）自分の発する言葉の重要性を意識した上で、部署のビジョン・方向性を示す機会を定期的につくりメンバーと共有している。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q3_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）チーム全員が協力して目標に向かうよう団結力とやる気を高めるための定期的な面談やミーティングを実施している。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q4_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【企画推進力】<br>        長期的視点での部署運営より高い課題、ハードルに挑戦し克服していこうとする力<br><br>        （１）現状に満足することなく、何事にも積極的に新しいことへ挑戦し成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q4_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）物事、状況を常により良く改善していこうという意識を持ち、それを日々の行動にうつしている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q4_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）自分たちの顧客は誰か、エンドユーザーは誰かを常に考え、そのニーズに応えるために迅速かつ積極的に対応している。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q4_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）現場のニーズを常に把握し、現場力が最大限に発揮されるために必要なものは何かを判断し提供している。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q4_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）状況に最も適したタイミングの良い計画・スケジュール化ができている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q5_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【経営感覚・経営貢献】<br>        業績に関心を持ち自部署だけでなく法人の利益のための広い視野で物事を考える力<br><br>        （１）法人の業績に関心を持ち、自分や自部署だけでなく法人全体の利益のためにというひろい視野で物事を考えている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q5_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）組織全体に利益をもたらす意思決定（意思決定のための調整も含め）がすばやくできる。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q5_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）経営方針を理解し、貢献を意識した部署目標を設定し、部署としての成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q5_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）組織の長期的な利益に対しては、自部署の短期的利益も犠牲にできる視点を持った発言、行動、判断ができている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q5_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）リスクマネジメント、医療事故防止、院内感染対策の必要性を理解し安全管理の方策を身につけ危機管理に積極的に参加している。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q6_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【マネジメント力・組織管理能力】<br>        表面的な情報だけでなく、自分自身の考察を加え、真の課題、問題を的確に捉え、解決策を見出し、チーム全体で行動を促す力<br><br>        （１）仕事の進行につき問題が生じないように常に気を配り、部下への助言や援助を行っている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q6_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）常に広い問題意識を持っており、現在の仕事に問題が生じそうなときは早め早めに手を打っている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q6_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）自らの感情をコントロールするだけでなく、周りの落ち着きも取り戻せるよう冷静に対処している。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q6_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）管理者としての役割を強く自覚しており、部下に対して模範となる行動・言動ができている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q6_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）複雑・困難な問題や突発的事態に対し、自己の責任において臨機応変な処置をとることができている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q1_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【コミュニケーション力】（情報伝達・発信力）<br>        自分の考えを相手に応じてわかりやすく的確に伝えられる。        組織において必要な情報を、的確にわかりやすく正確に伝える力。        自己の理論や企画を実行に移すために、関係者を説得、調整する力<br><br>        （１）自分の考えを相手に応じて、わかりやすく的確に伝えることができ、        また要点をついた説明ができる。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q1_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）業務が滞りなく行われるように、他部門との連携・調整がスムーズにできる。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q1_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）他部門（現場）が業務を円滑に進められるよう必要なサポートを行いまた、わかりやすい情報提供を行っている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q1_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）周りの空気を読み、自部署内および現場を含め法人全体の業務が円滑に進むための横串としての調整力に長けている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q1_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）相手の言いたいことをきちんと聞き、理解できている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q2_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【責任感】<br>        自己の責任を意識しそれを果たそうとする力<br><br>        （１）自分の失敗はチームの失敗であり、チームの失敗は、自分の失敗であると捉えて行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q2_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）自分の責任の範囲をきちんと理解し、自分の行う行動や行為、言動に責任を持った発言や行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q2_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）問題や課題に対して、自分事として捉え、他責にすることなく対処することができる。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q2_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）問題や課題に対して、自分事として捉え、他責にすることなく対処することができる。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q2_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）やや困難な状況に直面しても責任を回避したり、途中で挫折することはなく自己の任務を遂行している。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q3_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【人材育成】<br>        チームメンバーのやる気と生産性を高め、一人ひとりの成長を促す力<br><br>        （１）部下の意見に耳を傾け、部下に対し勇気づけや仕事への動機づけをはかっている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q3_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）組織運営において、メンバー一人ひとりの能力を把握し、部署目標達成のために的確な役割分担と指示、指導を行っている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q3_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）メンバーの先頭に立ち、より良いものを目指す心持ちや姿勢を、日常の発言や行動から模範を示している。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q3_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）自分の発する言葉の重要性を意識した上で、部署のビジョン・方向性を示す機会を定期的につくりメンバーと共有している。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q3_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）チーム全員が協力して目標に向かうよう団結力とやる気を高めるための定期的な面談やミーティングを実施している。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q4_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【企画推進力】<br>        長期的視点での部署運営より高い課題、ハードルに挑戦し克服していこうとする力<br><br>        （１）現状に満足することなく、何事にも積極的に新しいことへ挑戦し成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q4_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）物事、状況を常により良く改善していこうという意識を持ち、それを日々の行動にうつしている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q4_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）自分たちの顧客は誰か、エンドユーザーは誰かを常に考え、そのニーズに応えるために迅速かつ積極的に対応している。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q4_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）現場のニーズを常に把握し、現場力が最大限に発揮されるために必要なものは何かを判断し提供している。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q4_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）状況に最も適したタイミングの良い計画・スケジュール化ができている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q5_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【経営感覚・経営貢献】<br>        業績に関心を持ち自部署だけでなく法人の利益のための広い視野で物事を考える力<br><br>        （１）法人の業績に関心を持ち、自分や自部署だけでなく法人全体の利益のためにというひろい視野で物事を考えている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q5_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）組織全体に利益をもたらす意思決定（意思決定のための調整も含め）がすばやくできる。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q5_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）経営方針を理解し、貢献を意識した部署目標を設定し、部署としての成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q5_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）組織の長期的な利益に対しては、自部署の短期的利益も犠牲にできる視点を持った発言、行動、判断ができている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q5_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）リスクマネジメント、医療事故防止、院内感染対策の必要性を理解し安全管理の方策を身につけ危機管理に積極的に参加している。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q6_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='【マネジメント力・組織管理能力】<br>        表面的な情報だけでなく、自分自身の考察を加え、真の課題、問題を的確に捉え、解決策を見出し、チーム全体で行動を促す力<br><br>        （１）仕事の進行につき問題が生じないように常に気を配り、部下への助言や援助を行っている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q6_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）常に広い問題意識を持っており、現在の仕事に問題が生じそうなときは早め早めに手を打っている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q6_3',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（３）自らの感情をコントロールするだけでなく、周りの落ち着きも取り戻せるよう冷静に対処している。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q6_4',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（４）管理者としての役割を強く自覚しており、部下に対して模範となる行動・言動ができている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q6_5',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（５）複雑・困難な問題や突発的事態に対し、自己の責任において臨機応変な処置をとることができている。'),
        ),
    ]
