# Generated by Django 2.1.2 on 2019-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190609_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flag',
            field=models.NullBooleanField(default=None, verbose_name='入力完了フラグ'),
        ),
        migrations.AddField(
            model_name='item1',
            name='flag',
            field=models.NullBooleanField(default=None, verbose_name='入力完了フラグ'),
        ),
        migrations.AddField(
            model_name='item2',
            name='flag',
            field=models.NullBooleanField(default=None, verbose_name='入力完了フラグ'),
        ),
    ]
