# Generated by Django 2.1.2 on 2019-06-11 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_attribute_created_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='created_id',
        ),
        migrations.AddField(
            model_name='attribute',
            name='created_by3',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CreatedBy3', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
    ]
