# Generated by Django 2.1.2 on 2019-06-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_attribute_created_by3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='user',
        ),
        migrations.AddField(
            model_name='attribute',
            name='username',
            field=models.CharField(blank=True, default='', editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='created_by3',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CreatedBy3', to='app.Item', verbose_name='作成者'),
        ),
    ]
