# Generated by Django 2.1.2 on 2019-06-12 07:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190611_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='created_by3',
        ),
        migrations.AddField(
            model_name='attribute',
            name='userid',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid', to='app.Item', verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q4_2',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られる�����らいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（２）物事、状況を常により良く改善していこうという意識を持ち、それを日々の行動にうつしている。'),
        ),
    ]
