# Generated by Django 2.1.2 on 2019-06-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190612_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='userid',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid', to='app.Item'),
        ),
    ]
