# Generated by Django 2.1.2 on 2019-06-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190612_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='Itemkey',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Itemkey', to='app.Item'),
        ),
    ]
