# Generated by Django 2.1.2 on 2019-06-14 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190614_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Q1_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）自分の考えを相手に応じて、わかりやすく的確に伝えることができ、        また要点をついた説明ができる。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q2_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）自分の失敗はチームの失敗であり、チームの失敗は、自分の失敗であると捉えて行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q3_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）部下の意見に耳を傾け、部下に対し勇気づけや仕事への動機づけをはかっている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q4_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）現状に満足することなく、何事にも積極的に新しいことへ挑戦し成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q5_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）法人の業績に関心を持ち、自分や自部署だけでなく法人全体の利益のためにというひろい視野で物事を考えている。'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Q6_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）仕事の進行につき問題が生じないように常に気を配り、部下への助言や援助を行っている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q1_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）自分の考えを相手に応じて、わかりやすく的確に伝えることができ、        また要点をついた説明ができる。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q2_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）自分の失敗はチームの失敗であり、チームの失敗は、自分の失敗であると捉えて行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q3_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）部下の意見に耳を傾け、部下に対し勇気づけや仕事への動機づけをはかっている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q4_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）現状に満足することなく、何事にも積極的に新しいことへ挑戦し成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q5_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）法人の業績に関心を持ち、自分や自部署だけでなく法人全体の利益のためにというひろい視野で物事を考えている。'),
        ),
        migrations.AlterField(
            model_name='item1',
            name='Q6_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）仕事の進行につき問題が生じないように常に気を配り、部下への助言や援助を行っている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q1_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）自分の考えを相手に応じて、わかりやすく的確に伝えることができ、        また要点をついた説明ができる。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q2_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）自分の失敗はチームの失敗であり、チームの失敗は、自分の失敗であると捉えて行動ができている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q3_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）部下の意見に耳を傾け、部下に対し勇気づけや仕事への動機づけをはかっている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q4_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）現状に満足することなく、何事にも積極的に新しいことへ挑戦し成果をだしている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q5_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）法人の業績に関心を持ち、自分や自部署だけでなく法人全体の利益のためにというひろい視野で物事を考えている。'),
        ),
        migrations.AlterField(
            model_name='item2',
            name='Q6_1',
            field=models.IntegerField(choices=[(5, 'S：他者の模範となるくらいのレベルで行動できている'), (4, 'A：他者からみても、高評価を得られるくらいのレベルで行動できている'), (3, 'B：ほぼ、行動できている'), (2, 'C：やや足りないが努力している'), (1, 'D：まだ足りない')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='（１）仕事の進行につき問題が生じないように常に気を配り、部下への助言や援助を行っている。'),
        ),
    ]
